### ISSUE TITLE
Can you target multiple elements?

### ISSUE THREAD

**Issue by aaronstezycki** [Twikito/easy-toggle-state#103]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to target both the `<html>` and an `<div>` element, so that I can manipulate both nodes.

**Describe the solution you'd like**
When I click a trigger, I would like to add a class on the `<html>` element, and on the `<div>` element.
For eg. `modal--is-active` class. This means I can trigger overflow hidden on the html to stop the viewport moving, whilst also activating the modal as well.

**Describe alternatives you've considered**
I don't think this is possible yet.

**Comment by Twikito** [comment]
Hi @aaronstezycki 👋 
Thanks for taking time to send this question.

Since `data-toggle-target` accept a valid CSS selector string, containing one or more selectors to match, you can add whatever you want, so for instance in your example, `data-toggle-target="html, div.something"`.

Happy toggling 🤘

**Comment by aaronstezycki** [comment]
Oh, I didn't realise you could do this. The examples only cater to one selector at the minute. A little bit of description in the docs would help this :)

Thanks

**Comment by Twikito** [comment]
Good advice. I'll do that.
