### ISSUE TITLE
JavaScript Event hooks

### ISSUE THREAD

**Issue by mattmccarley** [Twikito/easy-toggle-state#14]
Is there any way to expose before, after, on event hooks? I'm trying to avoid animating max-height and animate an explicit height that is set by JavaScript.

**Comment by Twikito** [comment]
Thanks for taking time to report this issue.
I know that issue so well!
If I understand well what you would like, apply defined JS calculated styles at the same time of toggling the class would make the job, right?

**Comment by mattmccarley** [comment]
The max-height problem is only one instance of a use-case where this would be useful.

What we really want are exposed events like beforeToggleOn, beforeToggleOff, afterToggleOn, afterToggleOff, onToggleOn, onToggleOff.

**Comment by Twikito** [comment]
I am looking for a solution.
Anyway, I think a `data-toggle-style` could be a good idea.

**Comment by Twikito** [comment]
Ok. I have tested and implemented a solution: each trigger and target element will fire an event before and after toggling, so you will be able to add event listeners, and test the state of the element if toggled on or off.
Sounds good for you?

**Comment by dnwhte** [comment]
Works for me!

**Comment by Twikito** [comment]
Great! I just have to document this before merge.

**Comment by Twikito** [comment]
Done! https://twikito.github.io/easy-toggle-state/#expert
