### ISSUE TITLE
data-toggle-group with data-toggle-outside does not work

### ISSUE THREAD

**Issue by jenstornell** [Twikito/easy-toggle-state#16]
Overall, this lib works great. However I could not get it work with `data-toggle-outside`. Does it work with `data-toggle-group`?

**My code**

I've shorten it down a bit to only include the important parts.

```html
<li data-toggle-class="active" data-toggle-target="widget-create-file" data-toggle-group="tabsGroup" data-toggle-outside>
</li>
<li data-toggle-class="active" data-toggle-target="widget-create-folder" data-toggle-group="tabsGroup" data-toggle-outside>
</li>

<widget-create-file>
</widget-create-file>

<widget-create-folder>
</widget-create-folder>
```

What I want is that when I click outside of both my buttons and my targets, my targets should hide no matter what the current state is.

I use Google Chrome latest on Windows.

I also tried a few other crazy things that did not work, like this:

```html
<body data-toggle-trigger-off data-toggle-group="tabsGroup">
```

Any ideas?

I could do it with javascript, but it would be nice to be able to pull it off with this lib.

**Comment by Twikito** [comment]
Thanks for taking time to report this issue.
An element with `data-toggle-trigger-off` attribute must be placed __inside__ a target element.
I think this should work:
```html
<li data-toggle-class="active" data-toggle-target="widget-create-file" data-toggle-group="tabsGroup" data-toggle-outside>
</li>
<li data-toggle-class="active" data-toggle-target="widget-create-folder" data-toggle-group="tabsGroup" data-toggle-outside>
</li>

<widget-create-file>
    <button data-toggle-trigger-off></button>
</widget-create-file>

<widget-create-folder>
    <button data-toggle-trigger-off></button>
</widget-create-folder>
```
