### ISSUE TITLE
Unbind or destroy an instance?

### ISSUE THREAD

**Issue by dnwhte** [Twikito/easy-toggle-state#17]
Is there a way to unbind/destroy and reinit an easy-toggle instance? My scenario is that I want to use easy toggle on an element on mobile, but not on desktop. I was thinking in my JS on screen resize I could destroy or reinit the instance depending on the screen size.

**Comment by Twikito** [comment]
Sorry for the delay, I was on vacations. I'm checking if that is possible.

**Comment by Twikito** [comment]
Ok @danwhite85, I have a question: in your scenario, is there only on trigger inside the entire page, or several?
In this case, you could lazyload EasyToggleState after checking if you are on mobile device, right?

**Comment by dnwhte** [comment]
There are several. If it doesn't fit within the goals of this script, then no worries. I've created my own lightweight version to use in special cases. I image others may want the same functionality though.

**Comment by Twikito** [comment]
Indeed, it's a feature that is not available at the moment, as all triggers are initialized at the same time for simplicity.
That said, I will try to add this feature. I already know that means rewriting a big part of the script.

**Comment by jenstornell** [comment]
@Twikito If you with the latest update keep track of all the events (not sure if you do), then it should be much easier destroy the events and that way solve this issue. Then all that is left is to remove some data attributes and classes?

**Comment by Twikito** [comment]
@jenstornell, now, `window.initEasyToggleState()` returns an array of initialized trigger elements. Maybe that could help?

**Comment by aaronstezycki** [comment]
Hi all, I'm also looking for this type of functionality... I've turned my website into a SPA and this injects new content into a specific DOM node. When doing that, I need to be able to re-run the initialisation of toggle-state to capture new triggers. Is there any way to do this at this moment in time?

**Comment by Twikito** [comment]
Hi @aaronstezycki!
For now, you can `window.initEasyToggleState()`. It will initiate only non-initialized trigger elements, and return an array with new initialized elements.

**Comment by Twikito** [comment]
Hey folks @dnwhte @jenstornell @aaronstezycki 👋 

I'm glad to annonce you that the job is done: you can now use Easy Toggle State in ESM projects, and unbind triggers as you need!
Learn more in the [new API section in the documentation](https://twikito.github.io/easy-toggle-state/#api).
