### ISSUE TITLE
data-toggle-trigger-off doesn't work when child element is clicked

### ISSUE THREAD

**Issue by dnwhte** [Twikito/easy-toggle-state#18]
data-toggle-trigger-off doesn't work when child element is clicked.

See the example here. I've wrapped the text inside the links in a span. Click them longer closes the menu.
https://codepen.io/danwhite85/pen/gdEqJw

**Comment by Twikito** [comment]
Sorry for the delay, I was on vacations. I'm on it.

**Comment by Twikito** [comment]
Ok, now it works properly. Thanks for the report.
