### ISSUE TITLE
IE 11 emulator edge

### ISSUE THREAD

**Issue by unijez** [Twikito/easy-toggle-state#19]
I'm getting this console error when trying to test easy toggle in IE11 with emulator Edge set on the compatibility mode.
![screen shot 2018-10-15 at 12 56 00 pm](https://user-images.githubusercontent.com/34505504/46949719-4ced2e80-d07a-11e8-8952-eb47c5544301.png)
![screen shot 2018-10-15 at 12 55 30 pm](https://user-images.githubusercontent.com/34505504/46949720-4ced2e80-d07a-11e8-8c94-e7ba5eef0ff8.png)

**Comment by Twikito** [comment]
Thanks for taking time to report this issue.

According to MDN, this feature is not compatible with Internet Explorer: https://developer.mozilla.org/en-US/docs/Web/API/Event/Event#Browser_compatibility

But, [as mentioned in Easy Toggle State's documentation](https://twikito.github.io/easy-toggle-state/#compatibility), compatibility for Internet Explorer can be provided by [polyfill.io](https://polyfill.io/).

According to polyfill.io documentation, you can add compatibility for `Event` down to Internet Explorer 7: https://polyfill.io/v2/docs/features/#Event.

Hope that helps.

**Comment by unijez** [comment]
Perfect thank you.
