### ISSUE TITLE
Help to install the library

### ISSUE THREAD

**Issue by florianbouvot** [Twikito/easy-toggle-state#20]
Hi @Twikito,

It's not an issue with your library: everything works with direct download. 
But I want to use it in my workflow ([Gulp 4 with basic JS task](https://github.com/florianbouvot/aperitif/blob/master/gulpfile.js#L69)) so I'm wondering how I can use `import` or `require`? Can you give me some advice?

Thank you.

**Comment by Twikito** [comment]
Thanks for taking time to report this issue.

I think you should just add `"./node_modules/easy-toggle-state/dist/easy-toggle-state.js",` at line 79 of your package.json, and it should be done.

**Comment by florianbouvot** [comment]
@Twikito sorry, that's what I was doing first but it didn't work. 
I just understood that it's because I use `async` on `<script>`.

Edit: Like mentioned in your doc `window.initEasyToggleState();` works ☺️

**Comment by Twikito** [comment]
👍
