### ISSUE TITLE
Warning in console log if no data-toggle-class is found

### ISSUE THREAD

**Issue by jenstornell** [Twikito/easy-toggle-state#21]
When using Ajax, which means I get the results later I get this on init:

>Easy Toggle State is not used: there's no trigger with 'data-toggle-class' attribute to initialize.

While the information is correct, I'm well aware of this, because I trigger the function `window.initEasyToggleState();` at a later point in time.

So I guess this is a question. Is this warning really needed? To me it's kind of bloating my console log.

**Comment by Twikito** [comment]
Thanks for taking time to report this issue.

You're right. Maybe this warning is not so useful.

**Comment by Twikito** [comment]
Fixed!
