### ISSUE TITLE
Programmically fire toggle, open and close on element

### ISSUE THREAD

**Issue by jenstornell** [Twikito/easy-toggle-state#25]
When making things I noticed a missing feature.

Let's say I have a chain of events and after they are done I need to open, close or toggle a special element. In this case the toggle is not made by user interaction, but by the application itself.

**What I miss is these functions:**

```js
EasyToggleStateTrigger('open', element);
EasyToggleStateTrigger('close', element);
EasyToggleStateTrigger('toggle', element);
```

**or**

```js
openEasyToggleState(element);
closeEasyToggleState(element);
toggleEasyToggleState(element);
```

but I prefer the first one better. What do you think?

**Comment by Twikito** [comment]
Hi again!

I think you just need to `dispatchEvent(new Event('yourEvent'))`, with the event you specified, isn't it?

**Comment by jenstornell** [comment]
That looks harder a bit than what I have at the moment.

**To close I do this:**

```js
document.body.click();
```

**To open (with click) I do this:**

```js
let element = document.querySelector('.dropdown');
element.click();
```

**Double click is a bit harder:**

```js
let element = document.querySelector('.dropdown');
let event = new MouseEvent('dblclick', {
  'view': window,
  'bubbles': true,
  'cancelable': true
});
element.dispatchEvent(event);
```

It works fine so this issue is not super important.

*I always use ES6 by the way*

**Comment by Twikito** [comment]
Great! Maybe I'll add this feature anyway.
