### ISSUE TITLE
Clicking on a child element closes toggle

### ISSUE THREAD

**Issue by multiplehats** [Twikito/easy-toggle-state#28]
Hey there,

First off, love this little plugin/script. Such a huge time saver :)

I've added a toggle for a `<div>` which essentially is a menu with `<li>`'s etc.

However, whenever it toggles, and I want to click a link it toggles the actual element.

Edit: There was the same selector `#userDropdown` on both parent elements. Oops 🤔. However, issue remains after removing that.

```
<div aria-controls="userDropdown" aria-expanded="false" aria-haspopup="true" class=
"topbar-user openPopoverOnClick is-hidden-touch" data-toggle-class="show-popover"
data-toggle-target="#userDropdown" data-toggle-target-only="">
  
<div aria-hidden="true" aria-labelledby="userDropdown" class=
  "popover popover--default popover--m popover--bottom popover--rightAligned transparentScrollbar-Y ps ps--theme_default"
  id="userDropdown" role="listbox">
    <li><a href="/contact">Contact</a></li>
    <li><a href="/home">Home</a></li>
    <li><a href="/about">About</a></li>
  </div>

</div>
```

Am I missing something in the docs? Here's a GIF for more context. 

![Screen Recording 2019-05-04 at 06 59 PM](https://user-images.githubusercontent.com/24393137/57182458-975fbc80-6e9f-11e9-897e-57b4eb479758.gif)

**Comment by Twikito** [comment]
Hi @chrisschwartze!
Thanks for taking time reporting this issue.

In your code, the problem is that you have added the EasyToggleState attributes on the container, so when you click on a link inside, you click again on the container too!

You should do something like that:
```
<div class="topbar-user">
    <button type="button" aria-controls="userDropdown" aria-expanded="false" aria-haspopup="true" class="openPopoverOnClick is-hidden-touch" data-toggle-class="show-popover" data-toggle-target="#userDropdown" data-toggle-target-only="">
        User icon
    </button>
    <ul aria-hidden="true" aria-labelledby="userDropdown" class="popover popover--default popover--m popover--bottom popover--rightAligned transparentScrollbar-Y ps ps--theme_default" id="userDropdown" role="listbox">
        <li><a href="/contact">Contact</a></li>
        <li><a href="/home">Home</a></li>
        <li><a href="/about">About</a></li>
    </ul>
</div>
```

Hope that helps.
