### ISSUE TITLE
Problem in iOS 9.3.5

### ISSUE THREAD

**Issue by Zubrik** [Twikito/easy-toggle-state#29]
The library doesn't work in this OS version (iOS 9.3.5). I thought it was a problem with my site (I'm using the ES5 version), but your examples don't work either.

Is that a problem that should be solved with polyfill.io? What steps should I take to solve this problem?

Thank you very much.

**Comment by Twikito** [comment]
Hi @Zubrik,

According to Caniuse (https://caniuse.com/element-closest), ES6 version should work on iOS 9.3.5, but yes, if it doesn't, polyfill.io will solve that issue.

I think you should start here: https://polyfill.io/v3/url-builder/
