### ISSUE TITLE
Multiple tabs on page within accordion not targeting correctly?

### ISSUE THREAD

**Issue by jezthomp** [Twikito/easy-toggle-state#40]
I have two different tab areas on the same page, they are defiantly using two different unique ID's but for some reason two panels cannot be open at the same time even though they are separate.

Is there anything else apart from a unique ID i need to check? The tab navigation itself is also separate to its content in the DOM i/e the tabs navigation is in a sidebar and the tab content is in the main page content.

**Comment by Twikito** [comment]
Hi!
You closed this issue before I could answer, so I think you found your answer, right?
