### ISSUE TITLE
Form inside modal/dialog, cannot tab into?

### ISSUE THREAD

**Issue by jezthomp** [Twikito/easy-toggle-state#43]
I have a form within a dialog popup, all tabbing working fine apart from when a form appears within the popup, is this a form issue or something i can tweak with easy-toggle?

The form tabs fine through the input fields when not in dialog popup.

**Comment by Twikito** [comment]
Hi @jezthomp,
Thanks for taking time reporting this issue.

Since the focusables item list is re-evaluated each time you press the <kbd>TAB</kbd> key, you should be able to navigate through all focusable items inside your modal, even if you add or remove some.

Can you show your code snippet?

**Comment by jezthomp** [comment]
Below is the source code, its just your example dialog with a formidable form with it, you can tab through the form if you click the first input field. Need to make it properly accessibly but launching the dialog with tab etc then get access to the form which currently i don't.

`

					<div class="example-dialog"
					id="dialog"
					role="dialog"
					aria-labelledby="dialogTitle"
					aria-describedby="dialogContent"
					aria-hidden="true">
					<section class="example-dialog-container">
					<header id="dialogTitle" class="example-dialog-header">
					Enquire Below...
					</header>
					<div id="dialogContent" class="example-dialog-content">
					
					
					<div class="frm_forms " id="frm_form_1_container" >
					<form enctype="multipart/form-data" method="post" class="frm-show-form  frm_js_validate  frm_pro_form  frm_ajax_submit  frm-admin-viewing " id="form_contact-form"  >
					<div class="frm_form_fields ">
					<fieldset>
					<legend class="frm_screen_reader">Contact Us</legend>

					<div class="frm_fields_container">
					<input type="hidden" name="frm_action" value="create" />
					<input type="hidden" name="form_id" value="1" />
					<input type="hidden" name="frm_hide_fields_1" id="frm_hide_fields_1" value="" />
					<input type="hidden" name="form_key" value="contact-form" />
					<input type="hidden" name="item_meta[0]" value="" />
					<input type="hidden" id="frm_submit_entry_1" name="frm_submit_entry_1" value="39fb07e47b" /><input type="hidden" name="_wp_http_referer" value="/form-test/" /><label for="frm_verify_1" class="frm_screen_reader frm_hidden">If you are human, leave this field blank.</label>
					<input type="text" class="frm_hidden frm_verify" id="frm_verify_1" name="frm_verify" value=""  />
					<div id="frm_field_1_container" class="frm_form_field form-field  frm_required_field frm_top_container frm_first frm_half">
    					<label for="field_qh4icy" id="field_qh4icy_label" class="frm_primary_label">Your Name
        <span class="frm_required">*</span>
    </label>
   					 <input type="text" id="field_qh4icy" name="item_meta[1]" value=""  data-reqmsg="This field cannot be blank." aria-required="true" data-invmsg="Name is invalid" autofocus="autofocus"  />
    
    
					</div>
					<div id="frm_field_3_container" class="frm_form_field form-field  frm_required_field frm_top_container frm_full">
    					<label for="field_29yf4d" id="field_29yf4d_label" class="frm_primary_label">Your Email
        <span class="frm_required">*</span>
   					 </label>
    					<input type="email" id="field_29yf4d" name="item_meta[3]" value=""  data-reqmsg="This field cannot be blank." aria-required="true" data-invmsg="Please enter a valid email address"  />
    
    
					</div>
					<div id="frm_field_5_container" class="frm_form_field form-field  frm_required_field frm_top_container frm_full">
    					<label for="field_9jv0r1" id="field_9jv0r1_label" class="frm_primary_label">Your Enquiry
        					<span class="frm_required">*</span>
    					</label>
    					<textarea name="item_meta[5]" id="field_9jv0r1" rows="5"  data-reqmsg="This field cannot be blank." aria-required="true" data-invmsg="Your Enquiry is invalid"  ></textarea>
    
    
					</div>
					<input type="hidden" name="item_key" value="" />
					<div class="frm_submit">

					<button class="frm_button_submit frm_final_submit" type="submit"   formnovalidate="formnovalidate">Send Enquiry</button>

					</div></div>
					</fieldset>
					</div>
					</form>
					</div>
					
				</div>
				<footer class="example-dialog-footer">
					<button type="button" data-toggle-trigger-off>close</button>
				</footer>
			</section>
		</div> `

**Comment by Twikito** [comment]
Ok, I found the solution. I'm on it.

**Comment by Twikito** [comment]
There was an issue because the first input in your form was an hidden type.

It's now fixed. Can you confirm?

**Comment by jezthomp** [comment]
Unfortunately it doesn't work for me still, same source code as above, just updated the link to easy toggle.

**Comment by Twikito** [comment]
This is weird. It works for me. Are you sure you have updated for 1.12.2?

It seems there's no issue with your code : https://codepen.io/Twikito/pen/GRKmWQN?editors=1000
