### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by nico3333fr** [Twikito/easy-toggle-state#5]
Hi @Twikito !

First, thanks for the superb work you can be proud of. 👍 

As the web is made by humans, I would like to suggest you that this URL become a nice text file: https://twikito.github.io/easy-toggle-state/humans.txt ;)

Cheers,
Nicolas

**Comment by Twikito** [comment]
Arf! Forgot that one! Thanks :)

**Comment by Twikito** [comment]
Done!
