### ISSUE TITLE
cdnjs maybe ?

### ISSUE THREAD

**Issue by kocoten1992** [Twikito/easy-toggle-state#79]
**Is your feature request related to a problem? Please describe.**
I think for small site, set up npm, compile it down, and include to the page is quite a bit of work :sweat_smile:

**Describe the solution you'd like**
maybe push to cdnjs, so anyone just quickly grasp that and done with that small task (if website ever get big enough to need dedicate fronted team)

**Comment by Twikito** [comment]
Hi @kocoten1992!
Thanks for taking time to add this comment.

Well, I guess you're right. I'll check that.

**Comment by Twikito** [comment]
Hi @kocoten1992!

Done! [Easy Toggle State is available on cdnjs](https://cdnjs.com/libraries/easy-toggle-state).
