### ISSUE TITLE
Possible to work on hover?

### ISSUE THREAD

**Issue by jezthomp** [Twikito/easy-toggle-state#93]
Love this little script.

Is it possible to make work on hover or is it always a click event?

Thank you 👍

**Comment by Twikito** [comment]
Hi @jezthomp 👋 

No, it doesn't work necessarily on click event. It's the default value, but you can specify another event, and even a different one for outside event.
Check https://twikito.github.io/easy-toggle-state/#data-toggle-event for further informations.
