### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by cyclissmo** [Twikito/easy-toggle-state#96]
Suggest listing supported browsers in the documentation page.

**Comment by Twikito** [comment]
Hi @cyclissmo 👋 
Thanks for your suggestion.
What do you think about this section in the documentation? https://twikito.github.io/easy-toggle-state/#compatibility
Maybe I should rename it?

**Comment by Twikito** [comment]
Hi again @cyclissmo 👋 

Ok, your suggestion made me think about this section, and it came to me that it was not enough, so I've updated it: https://twikito.github.io/easy-toggle-state/#browser-support.
I hope you now have all the information you want.

Happy toggling! 🖖
